defmodule ChatGPTCloud.Repo.Migrations.AddSwarmResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  then hand-trimmed: the generator doesn't know the `ocel_*` tables already
  exist (created by the hand-written
  `20260822000000_create_process_intelligence_tables.exs` migration, which
  predates ash_postgres snapshot tracking) and tried to `create table` them
  again. Left in place: the three tables that genuinely never had a
  migration yet (`qualifications`, `cost_observations`,
  `secret_credentials` — their resources existed before this change but no
  migration was ever generated for them), plus the three new
  swarmsh-derived tables.

  Second hand-correction (2026-08-29, docs/errc-tracker.md "Critical" item):
  this migration's `swarm_work_items` table name collided with the
  independently-developed plain-Ecto `ChatGPTCloud.SwarmCoordination.WorkItem`
  schema's own `swarm_work_items` table (created earlier by
  `20260826000000_create_swarm_coordination_tables.exs`) — two unrelated
  "swarm work" features landed on the same table name during a branch
  merge. `mix ecto.migrate` on a fresh database failed with Postgres 42P07
  (relation already exists) as originally committed. Renamed this
  migration's table (and its unique index) to
  `process_intelligence_swarm_work_items`, matching a corresponding rename
  in `ChatGPTCloud.ProcessIntelligence.SwarmWorkItem`'s `postgres do table`
  declaration — the newer, ash_postgres-generated resource yields the name
  to the older, already-consumed-elsewhere plain-Ecto one. This is a
  targeted hand-correction of an already-broken-as-committed migration, not
  a routine hand-edit of a working one; the properly-generated fix is still
  to run `mix ash_postgres.generate_migrations` in an environment with the
  Elixir/Postgres toolchain and confirm it reproduces this same rename (or
  a no-op if it already matches), then `mix ecto.migrate` against a fresh
  database to confirm 42P07 no longer occurs. Neither step has been run —
  no toolchain was available in the environment this fix was made in.
  """

  use Ecto.Migration

  def up do
    create table(:cost_observations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :observation_key, :text, null: false
      add :run_key, :text, null: false
      add :category, :text, null: false
      add :estimated_cost, :map, null: false
      add :basis, :map, null: false, default: %{}

      add :observed_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
    end

    create unique_index(:cost_observations, [:observation_key],
             name: "cost_observations_unique_cost_observation_index"
           )

    create table(:qualifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qualification_key, :text, null: false
      add :run_key, :text, null: false
      add :subject_repo, :text
      add :subject_sha, :text
      add :kind, :text, null: false, default: "process_intelligence"
      add :standing, :text, null: false, default: "UNKNOWN"
      add :result, :map, null: false, default: %{}

      add :requested_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :state, :text, null: false, default: "pending"
    end

    create unique_index(:qualifications, [:qualification_key],
             name: "qualifications_unique_qualification_key_index"
           )

    create table(:secret_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :credential_key, :text, null: false
      add :kind, :text, null: false
      add :digest, :text, null: false
      add :scopes, {:array, :text}, null: false, default: []
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec
      add :encrypted_secret, :binary, null: false
    end

    create unique_index(:secret_credentials, [:credential_key],
             name: "secret_credentials_unique_secret_credential_index"
           )

    create table(:swarm_agents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :agent_key, :text, null: false
      add :team_key, :text
      add :role, :text
      add :specialization, :text
      add :capacity, :float, default: 1.0
      add :current_work_key, :text
      add :last_heartbeat_at, :utc_datetime_usec
      add :performance_metrics, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "idle"
    end

    create unique_index(:swarm_agents, [:agent_key], name: "swarm_agents_unique_agent_key_index")

    create table(:swarm_teams, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :team_key, :text, null: false
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:swarm_teams, [:team_key], name: "swarm_teams_unique_team_key_index")

    create table(:process_intelligence_swarm_work_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :work_item_id, :text, null: false
      add :work_type, :text
      add :priority, :bigint, default: 50
      add :description, :text
      add :estimated_duration_secs, :bigint
      add :team_key, :text
      add :claimed_by_agent_key, :text
      add :claimed_at, :utc_datetime_usec
      add :attempt_count, :bigint, default: 0
      add :version, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "pending"
    end

    create unique_index(:process_intelligence_swarm_work_items, [:work_item_id],
             name: "process_intelligence_swarm_work_items_unique_work_item_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:process_intelligence_swarm_work_items, [:work_item_id],
                     name: "process_intelligence_swarm_work_items_unique_work_item_id_index"
                   )

    drop table(:process_intelligence_swarm_work_items)

    drop_if_exists unique_index(:swarm_teams, [:team_key],
                     name: "swarm_teams_unique_team_key_index"
                   )

    drop table(:swarm_teams)

    drop_if_exists unique_index(:swarm_agents, [:agent_key],
                     name: "swarm_agents_unique_agent_key_index"
                   )

    drop table(:swarm_agents)

    drop_if_exists unique_index(:secret_credentials, [:credential_key],
                     name: "secret_credentials_unique_secret_credential_index"
                   )

    drop table(:secret_credentials)

    drop_if_exists unique_index(:qualifications, [:qualification_key],
                     name: "qualifications_unique_qualification_key_index"
                   )

    drop table(:qualifications)

    drop_if_exists unique_index(:cost_observations, [:observation_key],
                     name: "cost_observations_unique_cost_observation_index"
                   )

    drop table(:cost_observations)
  end
end
