#!/usr/bin/env python3
"""Classify commits as substantive vs. template/noise, and report the ratio.

Grew out of an ERRC review of 28 automation-generated branches merged into
chatgpt-cloud-elixir on 2026-08-29: several branches carried 500-1900 commits
each, and the overwhelming majority matched a handful of repeated, near-content-
free subject templates (`receipt: Project v2 memory proxy`, `control(select):
read <X>`, `project-memory: snapshot R<N> <noun>`, single-assertion `test(ggen):
require ...` commits, etc.) generated by scheduled swarm/DfCM cells. That noise
is real (it is the swarm's evidence trail) but it drowns the reviewable, unique
work in the same branches.

This script is the mechanical version of the manual classification the ERRC
review did by hand: given a commit range, it buckets each commit subject against
known noise-template patterns and reports what fraction of the range is
substantive. It never blocks anything by itself — see docs/swarm-noise-budget.md
for how a caller (e.g. .github/workflows/repo-hygiene.yml) turns the ratio into
policy.

Usage:
    scripts/branch-commit-ratio.py --base origin/main --ref HEAD
    scripts/branch-commit-ratio.py --base origin/main --ref origin/some-branch --json
    scripts/branch-commit-ratio.py --base origin/main --ref HEAD --enforce --min-ratio 0.15
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Each pattern names the swarm-generated commit-subject family it recognizes.
# These were derived empirically from the 2026-08-29 branch survey; extend this
# list as new automation cells adopt new subject conventions rather than
# lowering --min-ratio to compensate.
NOISE_PATTERNS = [
    ("project-memory-receipt", re.compile(r"^receipt: Project v2 memory proxy")),
    ("control-loop-poll", re.compile(r"^control\((select|measure|fanout|cell\d*)\):")),
    (
        "project-memory-template-op",
        re.compile(
            r"^project-memory: (read|update|snapshot|start|repair|reconcile) R\d+"
        ),
    ),
    ("single-assertion-test", re.compile(r"^test\((ggen|runtime)\): (require|verify) ")),
    ("falsify-probe", re.compile(r"^test\(starter\): falsify ")),
]

NOISE_RE = re.compile("|".join(p.pattern for _, p in NOISE_PATTERNS))


def git(*args: str) -> str:
    return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True)


def classify(subject: str) -> str | None:
    for name, pattern in NOISE_PATTERNS:
        if pattern.search(subject):
            return name
    return None


def collect_subjects(base: str, ref: str) -> list[str]:
    try:
        out = git("log", "--format=%s", "--no-merges", f"{base}..{ref}")
    except subprocess.CalledProcessError as exc:
        print(f"BLOCKED: git log failed for {base}..{ref}: {exc}", file=sys.stderr)
        raise SystemExit(69)
    return [line for line in out.splitlines() if line]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True, help="base ref, e.g. origin/main")
    parser.add_argument("--ref", default="HEAD", help="ref to classify (default HEAD)")
    parser.add_argument(
        "--min-ratio",
        type=float,
        default=0.15,
        help="minimum substantive-commit ratio before this is flagged (default 0.15)",
    )
    parser.add_argument(
        "--enforce",
        action="store_true",
        help="exit non-zero when the ratio falls below --min-ratio (default: report only)",
    )
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    args = parser.parse_args()

    subjects = collect_subjects(args.base, args.ref)
    total = len(subjects)
    if total == 0:
        result = {
            "base": args.base,
            "ref": args.ref,
            "total": 0,
            "substantive": 0,
            "noise": 0,
            "ratio": 1.0,
            "noise_breakdown": {},
            "min_ratio": args.min_ratio,
            "verdict": "ALIVE",
        }
        print(json.dumps(result, indent=2) if args.json else "no commits in range — nothing to classify")
        return 0

    breakdown: dict[str, int] = {}
    substantive = 0
    for subject in subjects:
        label = classify(subject)
        if label is None:
            substantive += 1
        else:
            breakdown[label] = breakdown.get(label, 0) + 1

    noise = total - substantive
    ratio = substantive / total
    verdict = "ALIVE" if ratio >= args.min_ratio else "PARTIAL_ALIVE"

    result = {
        "base": args.base,
        "ref": args.ref,
        "total": total,
        "substantive": substantive,
        "noise": noise,
        "ratio": round(ratio, 4),
        "noise_breakdown": breakdown,
        "min_ratio": args.min_ratio,
        "verdict": verdict,
    }

    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"BRANCH_NOISE_RATIO base={args.base} ref={args.ref}")
        print(f"  total={total} substantive={substantive} noise={noise} ratio={ratio:.2%}")
        if breakdown:
            print("  noise breakdown:")
            for label, count in sorted(breakdown.items(), key=lambda kv: -kv[1]):
                print(f"    {label}: {count}")
        print(f"  verdict={verdict} (min_ratio={args.min_ratio:.0%})")

    if args.enforce and ratio < args.min_ratio:
        print(
            f"REFUSED_NOISE_BUDGET: substantive ratio {ratio:.2%} is below the "
            f"required {args.min_ratio:.0%} for {args.base}..{args.ref}",
            file=sys.stderr,
        )
        return 65

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
